-- Procedure 
-- language SQL
CREATE OR REPLACE PROCEDURE TEST_DROPCREATE_PROCEDURE()
LANGUAGE SQL
AS $$
	DROP TABLE IF EXISTS AAA;
	CREATE TABLE AAA (BBB CHAR(5) CONSTRAINT FIRSTKEY PRIMARY KEY);
$$;

CALL TEST_DROPCREATE_PROCEDURE();

-- Function
-- LANGUAGE PLPGSPL
CREATE OR REPLACE FUNCTION TEST_DROPCREATE_FUNCTION()
RETURNS VOID
LANGUAGE PLPGSQL
AS $$
BEGIN
	DROP TABLE IF EXISTS AAA;
	CREATE TABLE AAA (BBB CHAR(5) CONSTRAINT FIRSTKEY PRIMARY KEY, CCC CHAR(5));
	
	DROP TABLE IF EXISTS AAAB;
	CREATE TABLE AAAB (BBBA CHAR(5) CONSTRAINT SECONDKEY PRIMARY KEY, CCCA CHAR(5));
END
$$;

SELECT TEST_DROPCREATE_FUNCTION();